openapi: 3.0.3
info:
  title: Prices API
  description: API for querying applicable prices and rates.
  version: 1.0.0
  contact:
    name: Alexander Echavarría Perez
    email: alex.echavarria.perez@gmail.com
servers:
  - url: /api/v1
paths:
  /prices:
    get:
      tags:
        - prices
      summary: Find the price applicable to a product of a specific brand on a given date
      operationId: findApplicablePrice
      parameters:
        - name: applicationDate
          in: query
          required: true
          schema:
            type: string
            format: date-time
          description: Application date for the price
        - name: productId
          in: query
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
          description: Product identifier
        - name: brandId
          in: query
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
          description: Brand identifier
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceFindResponse'
        '404':
          description: Price not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
components:
  schemas:
    PriceFindResponse:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        brandId:
          type: integer
          format: int64
        priceList:
          type: integer
          format: int64
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        price:
          type: number
          format: double
        curr:
          type: string
    ApiErrorResponse:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        path:
          type: string
        timestamp:
          type: string
          format: date-time
